In [1]:
import torch
import numpy as np

a = torch.FloatTensor(3, 2)
a

tensor([[1.0893e-19, 4.5591e-41],
        [1.0893e-19, 4.5591e-41],
        [0.0000e+00, 0.0000e+00]])

In [2]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
torch.FloatTensor([[1, 2, 3], [3, 2, 1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [6]:
n = np.zeros(shape=(3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [10]:
torch.DoubleTensor(3, 2)

tensor([[5.3942e-315,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]], dtype=torch.float64)

In [11]:
n = np.zeros(shape=(3, 2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
n = np.zeros(shape=(3, 2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Scalar tensors

In [14]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [15]:
s = a.sum()
s

tensor(6)

In [16]:
s.item()

6

In [17]:
torch.tensor(1)

tensor(1)

## GPU tensors

In [18]:
a = torch.FloatTensor([2, 3])
a

tensor([2., 3.])

In [19]:
ca = a.to('cuda')
ca

tensor([2., 3.], device='cuda:0')

In [20]:
a + 1

tensor([3., 4.])

In [21]:
ca + 1

tensor([3., 4.], device='cuda:0')

In [22]:
ca.device

device(type='cuda', index=0)