In [1]:
import torch
import numpy as np

a = torch.FloatTensor(3, 2)
a

tensor([[-1.5013e+00,  4.5623e-41],
        [-1.5013e+00,  4.5623e-41],
        [-1.5014e+00,  4.5623e-41]])

In [2]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
torch.FloatTensor([[1, 2, 3], [3, 2, 1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [5]:
n = np.zeros(shape=(3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [7]:
torch.DoubleTensor(3, 2)

tensor([[4.3555e-315,  0.0000e+00],
        [3.8995e-315, 2.6525e-315],
        [3.9084e+160, 4.8873e+199]], dtype=torch.float64)

In [8]:
n = np.zeros(shape=(3, 2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
n = np.zeros(shape=(3, 2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Scalar tensors

In [10]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [11]:
s = a.sum()
s

tensor(6)

In [12]:
s.item()

6

In [13]:
torch.tensor(1)

tensor(1)

## GPU tensors

In [14]:
a = torch.FloatTensor([2, 3])
a

tensor([2., 3.])

In [15]:
ca = a.to('cuda')
ca

tensor([2., 3.], device='cuda:0')

In [16]:
a + 1

tensor([3., 4.])

In [17]:
ca + 1

tensor([3., 4.], device='cuda:0')

In [18]:
ca.device

device(type='cuda', index=0)

## Gradients

In [19]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])

In [20]:
v_sum = v1 + v2
v_sum

tensor([3., 3.], grad_fn=<AddBackward0>)

In [21]:
v_res = (v_sum*2).sum()
v_res

tensor(12., grad_fn=<SumBackward0>)

In [22]:
v1.is_leaf, v2.is_leaf

(True, True)

In [23]:
v_sum.is_leaf, v_res.is_leaf

(False, False)

In [24]:
v1.requires_grad

True

In [25]:
v2.requires_grad

False

In [26]:
v_sum.requires_grad

True

In [27]:
v_res.requires_grad

True

In [28]:
v_res.backward()
v1.grad

tensor([2., 2.])

In [29]:
v2.grad