In [1]:
import numpy as np
import ptan

q_vals = np.array([[1, 2, 3], [1, 1, 0]])
q_vals

/home/sannhtet/Desktop/Computer Science and AI/AI/Deep-Reinforcement-Learning-Hands-On/.venv/lib/python3.11/site-packages/ignite/handlers/checkpoint.py:16: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import ZeroRedundancyOptimizer


array([[1, 2, 3],
       [1, 1, 0]])

In [3]:
selector = ptan.actions.ArgmaxActionSelector()
selector(q_vals)

array([2, 0])

In [4]:
selector = ptan.actions.EpsilonGreedyActionSelector(epsilon=0.0, selector=ptan.actions.ArgmaxActionSelector())
selector(q_vals)

array([2, 0])

In [7]:
selector = ptan.actions.EpsilonGreedyActionSelector(epsilon=1.0, selector=ptan.actions.ArgmaxActionSelector())
selector(q_vals)

array([1, 0])

In [8]:
selector.epsilon

1.0

In [9]:
selector.epsilon = 0.0
selector(q_vals)

array([2, 0])

In [10]:
selector = ptan.actions.ProbabilityActionSelector()
for _ in range(10):
    acts = selector(np.array([
        [0.1, 0.8, 0.1],
        [0.0, 0.0, 1.0],
        [0.5, 0.5, 0.0]
    ]))
    print(acts)

[0 2 1]
[1 2 1]
[1 2 0]
[1 2 1]
[1 2 1]
[1 2 0]
[2 2 0]
[1 2 0]
[0 2 0]
[1 2 1]
