In [1]:
import ptan
import torch
from torch import nn
import numpy as np

/home/sannhtet/Desktop/Computer Science and AI/AI/Deep-Reinforcement-Learning-Hands-On/.venv/lib/python3.11/site-packages/ignite/handlers/checkpoint.py:16: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import ZeroRedundancyOptimizer


In [2]:
class DQNNet(nn.Module):
    def __init__(self, actions: int):
        super(DQNNet, self).__init__()
        self.actions = actions

    def forward(self, x):
        # we always produce diagonal tensor of shape
        # (batch_size, actions)
        return torch.eye(x.size()[0], self.actions)

In [3]:
net = DQNNet(actions=3)
net(torch.zeros(2, 10))

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [4]:
selector = ptan.actions.ArgmaxActionSelector()
agent = ptan.agent.DQNAgent(model=net, action_selector=selector)
agent(torch.zeros(2, 5))

(array([0, 1]), [None, None])

In [5]:
selector = ptan.actions.EpsilonGreedyActionSelector(epsilon=1.0)
agent = ptan.agent.DQNAgent(model=net, action_selector=selector)
agent(torch.zeros(10, 5))[0]

array([2, 2, 2, 0, 1, 2, 0, 1, 0, 1])

In [6]:
selector.epsilon = 0.5
agent(torch.zeros(10, 5))[0]

array([0, 1, 2, 0, 1, 0, 1, 1, 0, 0])

In [8]:
selector.epsilon = 0.1
agent(torch.zeros(10, 5))[0]

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 0])