In [1]:
from lib import *

/home/sannhtet/Desktop/Computer Science and AI/AI/Deep-Reinforcement-Learning-Hands-On/.venv/lib/python3.11/site-packages/ignite/handlers/checkpoint.py:16: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import ZeroRedundancyOptimizer


In [2]:
net = DQNNet()
net

DQNNet(
  (ff): Linear(in_features=5, out_features=3, bias=True)
)

In [3]:
net.ff.weight

Parameter containing:
tensor([[ 0.2031, -0.1227,  0.2434,  0.2945,  0.0009],
        [ 0.2138,  0.2066, -0.2145, -0.1012, -0.1998],
        [ 0.2198,  0.1173, -0.4043,  0.2484, -0.4009]], requires_grad=True)

In [4]:
tgt_net = ptan.agent.TargetNet(net)
print("Main net:", net.ff.weight)
print("Target net:", tgt_net.target_model.ff.weight)

Main net: Parameter containing:
tensor([[ 0.2031, -0.1227,  0.2434,  0.2945,  0.0009],
        [ 0.2138,  0.2066, -0.2145, -0.1012, -0.1998],
        [ 0.2198,  0.1173, -0.4043,  0.2484, -0.4009]], requires_grad=True)
Target net: Parameter containing:
tensor([[ 0.2031, -0.1227,  0.2434,  0.2945,  0.0009],
        [ 0.2138,  0.2066, -0.2145, -0.1012, -0.1998],
        [ 0.2198,  0.1173, -0.4043,  0.2484, -0.4009]], requires_grad=True)


In [5]:
net.ff.weight.data += 1.0
print("After update")
print("Main net:", net.ff.weight)
print("Target net:", tgt_net.target_model.ff.weight)

After update
Main net: Parameter containing:
tensor([[1.2031, 0.8773, 1.2434, 1.2945, 1.0009],
        [1.2138, 1.2066, 0.7855, 0.8988, 0.8002],
        [1.2198, 1.1173, 0.5957, 1.2484, 0.5991]], requires_grad=True)
Target net: Parameter containing:
tensor([[ 0.2031, -0.1227,  0.2434,  0.2945,  0.0009],
        [ 0.2138,  0.2066, -0.2145, -0.1012, -0.1998],
        [ 0.2198,  0.1173, -0.4043,  0.2484, -0.4009]], requires_grad=True)


In [6]:
tgt_net.sync()
print("After sync")
print("Main net:", net.ff.weight)
print("Target net:", tgt_net.target_model.ff.weight)

After sync
Main net: Parameter containing:
tensor([[1.2031, 0.8773, 1.2434, 1.2945, 1.0009],
        [1.2138, 1.2066, 0.7855, 0.8988, 0.8002],
        [1.2198, 1.1173, 0.5957, 1.2484, 0.5991]], requires_grad=True)
Target net: Parameter containing:
tensor([[1.2031, 0.8773, 1.2434, 1.2945, 1.0009],
        [1.2138, 1.2066, 0.7855, 0.8988, 0.8002],
        [1.2198, 1.1173, 0.5957, 1.2484, 0.5991]], requires_grad=True)


In [7]:
net.ff.weight.data += 1.0
net.ff.weight

Parameter containing:
tensor([[2.2031, 1.8773, 2.2434, 2.2945, 2.0009],
        [2.2138, 2.2066, 1.7855, 1.8988, 1.8002],
        [2.2198, 2.1173, 1.5957, 2.2484, 1.5991]], requires_grad=True)

In [8]:
tgt_net.target_model.ff.weight

Parameter containing:
tensor([[1.2031, 0.8773, 1.2434, 1.2945, 1.0009],
        [1.2138, 1.2066, 0.7855, 0.8988, 0.8002],
        [1.2198, 1.1173, 0.5957, 1.2484, 0.5991]], requires_grad=True)

In [9]:
tgt_net.alpha_sync(0.1)
tgt_net.target_model.ff.weight

Parameter containing:
tensor([[2.1031, 1.7773, 2.1434, 2.1945, 1.9009],
        [2.1138, 2.1066, 1.6855, 1.7988, 1.7002],
        [2.1198, 2.0173, 1.4957, 2.1484, 1.4991]], requires_grad=True)